cat <<EOF > environment.yml
name: isl-project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - yfinance
  - plotly
  - streamlit
  - pip
EOF