name: alpha-allocator
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyhd8ed1ab_1
  - backports.zstd=1.3.0=py313h18e8e13_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - brotli-python=1.2.0=py313hf159716_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cffi=2.0.0=py313hf01b4d8_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - curl-cffi=0.13.0=py313h3d68456_1
  - frozendict=2.4.7=py313h07c4f96_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libabseil=20250814.1=cxx17_hee66210_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.2.0=he0feb66_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.3=h5347b49_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lxml=6.0.2=py313h4a16004_2
  - multitasking=0.0.12=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.0=py313hf6604e3_0
  - openssl=3.6.0=h26f9b46_0
  - pandas=2.3.3=py313h08cd8bf_2
  - peewee=3.19.0=py313h386cab5_0
  - pip=25.3=pyh145f28c_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - protobuf=6.32.1=py313h50fafe1_2
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.5=hec9711d_102_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - six=1.17.0=pyhe01879c_1
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - tk=8.6.13=noxft_ha0e22de_103
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websockets=15.0.1=py313h54dd161_2
  - yfinance=1.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - click==8.3.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - narwhals==2.15.0
      - packaging==25.0
      - pillow==12.1.0
      - plotly==6.5.1
      - pyarrow==22.0.0
      - pydeck==0.9.1
      - pyparsing==3.3.1
      - referencing==0.37.0
      - rpds-py==0.30.0
      - scikit-learn==1.8.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - smmap==5.0.2
      - streamlit==1.52.2
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - tornado==6.5.4
      - watchdog==6.0.0
prefix: /opt/conda/envs/alpha-allocator
