name: alpha-allocator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - pip
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - streamlit
  - yfinance
  - joblib
  - pip:
    - -r requirements.txt